version: '3.7'
services:
  request-logger:
    build: ./request-logger
    ports:
      - '8080'
  prometheus:
    image: prom/prometheus:v2.16.0
    ports:
      - '9090'
  grafana-image-renderer:
    image: grafana/grafana-image-renderer:1.0.9
    ports:
      - 8081:8081
  grafana:
    image: grafana/grafana:6.7.0-beta1
    volumes:
      - /tmp/grafana-repro/grafana:/var/lib/grafana
    ports:
      - 3000:3000
    environment:
      - GF_LOG_FILTERS=rendering:debug
      - GF_RENDERING_SERVER_URL=http://grafana-image-renderer:8081/render
      - GF_RENDERING_CALLBACK_URL=http://grafana:3000
      - GF_EXTERNAL_IMAGE_STORAGE_PROVIDER=gcs
      - GF_EXTERNAL_IMAGE_STORAGE_GCS_KEY_FILE=/var/lib/grafana/keyfile.json
      - GF_EXTERNAL_IMAGE_STORAGE_GCS_BUCKET=grafana-images-test-martin
